"""
spsg/backtester.py
===================
Turns a generated strategy's parameters into a rule-based trading model, then
walk-forward backtests it on OHLC price history and computes the performance
metrics shown on the "My Algosark Strategy" dashboard page (backtested return,
CAGR, Sharpe, max drawdown, win rate, profit factor, total trades).

Data source
-----------
This container's network egress allow-list doesn't include market-data
providers, so `load_price_history` falls back to a seeded synthetic
Geometric-Brownian-Motion series when no `prices` argument is supplied. In
production, swap `load_price_history` for a real feed — the obvious source is
whatever brokerage API you're already connecting via `spsg/broker/`, since
Alpaca, Interactive Brokers, etc. all expose historical bars endpoints. Every
other function here operates on a plain float array, so nothing downstream
needs to change.

Trading rule
------------
The strategy parameters generated by the ensemble (holding_period_days,
risk_per_trade, leverage, max_drawdown_target) are translated into a simple,
transparent moving-average-crossover-with-volatility-filter rule. This keeps
the backtester auditable (a compliance reviewer can read exactly what trades
were taken and why) while still respecting the personalisation coming out of
SPSG: a "5-day holding period" profile trades a fast/slow MA pair, while a
"25-day holding period" profile trades a much slower pair.
"""

from __future__ import annotations
from dataclasses import dataclass
import numpy as np


def load_price_history(n_days: int = 1500, seed: int = 123, mu: float = 0.08, sigma: float = 0.20) -> np.ndarray:
    """Synthetic daily close-price series (placeholder until a real market-data /
    broker historical-bars feed is wired in)."""
    rng = np.random.default_rng(seed)
    dt = 1 / 252
    shocks = rng.normal((mu - 0.5 * sigma ** 2) * dt, sigma * np.sqrt(dt), size=n_days)
    return 100.0 * np.exp(np.cumsum(shocks))


def _ma_crossover_signal(prices: np.ndarray, fast: int, slow: int) -> np.ndarray:
    """Returns a position array: +1 long, -1 short, 0 flat, aligned to `prices`."""
    fast = max(2, int(fast))
    slow = max(fast + 1, int(slow))

    fast_ma = np.convolve(prices, np.ones(fast) / fast, mode="valid")
    slow_ma = np.convolve(prices, np.ones(slow) / slow, mode="valid")

    # Align lengths (valid convolution shortens the array)
    offset = len(prices) - len(slow_ma)
    fast_ma = fast_ma[-(len(slow_ma)):]

    raw_signal = np.sign(fast_ma - slow_ma)
    position = np.zeros(len(prices))
    position[offset:] = raw_signal
    return position


def _holding_period_to_ma_pair(holding_period_days: float) -> tuple[int, int]:
    """Maps the ensemble's continuous holding_period_days output to a sensible
    (fast, slow) moving-average pair. Shorter holding period -> faster MAs."""
    holding_period_days = np.clip(holding_period_days, 1, 30)
    fast = int(np.clip(holding_period_days * 0.4, 2, 12))
    slow = int(np.clip(holding_period_days * 1.6, fast + 3, 45))
    return fast, slow


def compute_current_signal(prices: np.ndarray, holding_period_days: float) -> dict:
    """
    Live/paper-trading counterpart to _ma_crossover_signal: instead of a full
    position array over history, returns just the *current* signal (+1 long,
    -1 short, 0 flat) implied by the latest bar, plus the MA values so a
    human/ops dashboard can sanity-check it. This is what spsg/live_runner.py
    calls on a schedule to decide whether to enter/exit/hold.
    """
    fast, slow = _holding_period_to_ma_pair(holding_period_days)
    if len(prices) < slow + 1:
        return {"signal": 0, "reason": "insufficient_history", "fast_ma": None, "slow_ma": None, "fast": fast, "slow": slow}

    fast_ma = prices[-fast:].mean()
    slow_ma = prices[-slow:].mean()
    signal = int(np.sign(fast_ma - slow_ma))
    return {"signal": signal, "fast_ma": float(fast_ma), "slow_ma": float(slow_ma), "fast": fast, "slow": slow}


@dataclass
class BacktestResult:
    total_return_pct: float
    cagr_pct: float
    sharpe_ratio: float
    max_drawdown_pct: float
    win_rate_pct: float
    profit_factor: float
    total_trades: int
    equity_curve: list[float]
    period_start_idx: int
    period_end_idx: int

    def to_dict(self) -> dict:
        d = self.__dict__.copy()
        # Keep equity curve short for API payloads (dashboard only needs a sparkline)
        d["equity_curve"] = _downsample(d["equity_curve"], max_points=120)
        return d


def _downsample(series: list[float], max_points: int = 120) -> list[float]:
    if len(series) <= max_points:
        return series
    idx = np.linspace(0, len(series) - 1, max_points).astype(int)
    return [series[i] for i in idx]


def run_backtest(
    prices: np.ndarray,
    holding_period_days: float,
    risk_per_trade_pct: float,
    leverage: float,
    max_drawdown_target_pct: float,
    trading_days_per_year: int = 252,
) -> BacktestResult:
    """
    Rule-based backtest of a moving-average crossover strategy parameterised by
    the SPSG ensemble's output. Position sizing scales with risk_per_trade_pct
    and leverage; a max_drawdown_target_pct circuit breaker flattens the book
    (de-risks to cash) once breached, then allows re-entry.
    """
    fast, slow = _holding_period_to_ma_pair(holding_period_days)
    position = _ma_crossover_signal(prices, fast, slow)

    rets = np.diff(prices) / prices[:-1]
    position = position[:-1]  # align: position[t] earns rets[t] (next-bar return)

    size = (risk_per_trade_pct / 100.0) * leverage * 10  # scales exposure per unit risk budget
    size = np.clip(size, 0.05, 3.0)  # sane exposure bounds

    strat_rets = position * size * rets

    equity = np.cumprod(1 + strat_rets)
    running_peak = np.maximum.accumulate(equity)
    drawdown = (equity - running_peak) / running_peak

    # Circuit breaker: once max_drawdown_target is breached, zero out returns
    # until equity recovers back above (1 - target) * peak (de-risk-and-wait).
    target_dd = -abs(max_drawdown_target_pct) / 100.0
    breached = drawdown <= target_dd
    if breached.any():
        strat_rets_adj = strat_rets.copy()
        in_breach = False
        for i in range(len(strat_rets_adj)):
            if breached[i]:
                in_breach = True
            if in_breach:
                strat_rets_adj[i] = 0.0
                if i > 0 and drawdown[i] > target_dd * 0.5:  # recovered halfway -> resume
                    in_breach = False
        equity = np.cumprod(1 + strat_rets_adj)
        strat_rets = strat_rets_adj
        running_peak = np.maximum.accumulate(equity)
        drawdown = (equity - running_peak) / running_peak

    total_return_pct = (equity[-1] - 1) * 100 if len(equity) else 0.0
    n_years = len(prices) / trading_days_per_year
    cagr_pct = ((equity[-1]) ** (1 / max(n_years, 1e-6)) - 1) * 100 if len(equity) else 0.0

    vol = strat_rets.std()
    sharpe = (strat_rets.mean() / vol * np.sqrt(trading_days_per_year)) if vol > 1e-9 else 0.0

    max_dd_pct = drawdown.min() * 100 if len(drawdown) else 0.0

    # Trade-level stats: a "trade" = a contiguous run of non-zero, same-sign position
    trades = []
    cur_sign, cur_ret = 0, 0.0
    for pos, r in zip(position, strat_rets):
        s = np.sign(pos)
        if s == 0:
            if cur_sign != 0:
                trades.append(cur_ret)
                cur_sign, cur_ret = 0, 0.0
            continue
        if s != cur_sign and cur_sign != 0:
            trades.append(cur_ret)
            cur_ret = 0.0
        cur_sign = s
        cur_ret += r
    if cur_sign != 0:
        trades.append(cur_ret)

    trades = np.array(trades)
    wins = trades[trades > 0]
    losses = trades[trades <= 0]
    win_rate_pct = (len(wins) / len(trades) * 100) if len(trades) else 0.0
    gross_win = wins.sum() if len(wins) else 0.0
    gross_loss = abs(losses.sum()) if len(losses) else 1e-9
    profit_factor = gross_win / gross_loss if gross_loss > 0 else float("inf")

    return BacktestResult(
        total_return_pct=float(total_return_pct),
        cagr_pct=float(cagr_pct),
        sharpe_ratio=float(sharpe),
        max_drawdown_pct=float(max_dd_pct),
        win_rate_pct=float(win_rate_pct),
        profit_factor=float(min(profit_factor, 99.99)),
        total_trades=int(len(trades)),
        equity_curve=(equity * 10000).tolist(),  # scaled to a notional £10,000 start, matches paper-trading UI
        period_start_idx=0,
        period_end_idx=len(prices) - 1,
    )


def walk_forward_backtest(
    prices: np.ndarray,
    holding_period_days: float,
    risk_per_trade_pct: float,
    leverage: float,
    max_drawdown_target_pct: float,
    n_folds: int = 4,
) -> dict:
    """
    Splits `prices` into n_folds contiguous, non-overlapping windows and runs
    run_backtest on each, then reports both the full-period result and the
    per-fold Sharpe ratios (used by detect_drift to flag when the most recent
    fold's performance has diverged materially from the historical average —
    the basis of Algosark's "continuous strategy optimisation framework").
    """
    full = run_backtest(prices, holding_period_days, risk_per_trade_pct, leverage, max_drawdown_target_pct)

    fold_size = len(prices) // n_folds
    fold_sharpes = []
    for i in range(n_folds):
        start = i * fold_size
        end = len(prices) if i == n_folds - 1 else (i + 1) * fold_size
        fold_prices = prices[start:end]
        if len(fold_prices) < 30:
            continue
        fold_result = run_backtest(fold_prices, holding_period_days, risk_per_trade_pct, leverage, max_drawdown_target_pct)
        fold_sharpes.append(fold_result.sharpe_ratio)

    return {
        "full_period": full.to_dict(),
        "fold_sharpes": fold_sharpes,
        "n_folds": n_folds,
    }


def detect_drift(fold_sharpes: list[float], z_threshold: float = 1.5) -> dict:
    """
    Flags performance drift if the most recent fold's Sharpe is more than
    `z_threshold` standard deviations below the mean of the prior folds.
    This is the mechanism behind the dashboard's "drift detection" /
    "consent-based strategy updates" behaviour: when this returns
    needs_review=True, the platform should prompt the user for consent
    before retraining/re-generating their strategy (see api_strategy.py).
    """
    if len(fold_sharpes) < 3:
        return {"needs_review": False, "reason": "insufficient_history"}

    *prior, latest = fold_sharpes
    mean_prior = float(np.mean(prior))
    std_prior = float(np.std(prior)) or 1e-6
    z = (latest - mean_prior) / std_prior

    return {
        "needs_review": bool(z < -z_threshold),
        "z_score": float(z),
        "latest_sharpe": float(latest),
        "prior_mean_sharpe": mean_prior,
    }
